FROM amazoncorretto:11
WORKDIR /app
COPY /order-management-service/target/order-management-service.jar /app/
COPY /order-management-service/src/main/resources/application-prod.yml /app/
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/app/order-management-service.jar"]
