FROM amazoncorretto:11
WORKDIR /app
COPY /order-management-service/target/quality-management-service.jar /app/
COPY /order-management-service/src/main/resources/application-dev.yml /app/
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=dev", "/app/order-management-service.jar"]