multitenancy:
  schema-cache:
    maximumSize: '100'
    expireAfterAccess: '10'
  tenant:
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml
    entityManager:
      packages: com.groyyo.order.management.service.domain
    module: qc
    repository:
      packages: com.groyyo.order.management.service.repository
  master:
    repository:
      packages: com.groyyo.service.multitenancy.repository
    liquibase:
      enabled: 'false'
    entityManager:
      packages: com.groyyo.service.multitenancy.domain
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://groyyo-postgres-db.postgres.database.azure.com:5432/postgres
    username: groyyopgadmin@groyyo-postgres-db
    password: J-Y@WnAh8nJ#k2D%
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
server:
  port: 9081
azure:
  storage:
    ConnectionString: DefaultEndpointsProtocol=https;AccountName=groyyotenantstorage;AccountKey=Z0C14b9x66WuW5VcuAgt0vKMaC7bVlxqxQXcGaoZvyaCE+ZTKuqs39BWbjQhx9wASjUn86wRbIXP+AStnElvag==;EndpointSuffix=core.windows.net
