############# Application Context ###############
server:
  port: '8008'
  servlet:
    context-path: /order-management-service
  tomcat:
    max-threads: '50'
    accesslog:
      enabled: 'true'
      prefix: order-management-service
      pattern: '%h %l %u %t "%r" %I %s %b %F %D'
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: 'true'
      directory: /var/log/groyyo
  error:
    include-message: always
    
########## Auth Config ##############
#enable:
#  cors: 'true'
#  authorize: 'false'
#  authentication: 'false'

########## Cache Config ##############
cache:
  masterData:
    enable: 'true'

########## Services URL's ##############
service:
  user:
    url: http://user-service/user-service/
  masterData:
    url: http://master-data-service/master-data-service
  file_management:
      url: http://file-management-service/file-management-service

############## Hibernate Configuration ##############
hibernate:
  format_sql: 'true'
  dialect: org.hibernate.dialect.PostgreSQL92Dialect
  order_inserts: 'true'
  order_updates: 'true'
  cache:
    provider_class: org.hibernate.cache.NoCacheProvider
  hbm2ddl:
    auto: update
  show_sql: 'false'

################# Postgresql JDBC Connection config ###############
jdbc:
  max:
    statements: 240
    idle:
      time:
        excess:
          connections: 2
      timing: 30
    pool:
      size: '2'
  min:
    pool:
      size: '2'
  test:
    connection:
      on:
        checkin: true
  initial:
    pool:
      size: '2'
  driver:
    class:
      name: org.postgresql.Driver
  preferred:
    test:
      query: SELECT 1
  acquire:
    increment: '2'
  master:
    url:  jdbc:postgresql://groyyo-postgres-db-dev.postgres.database.azure.com:5432/order_management_service
    username: groyyopgadmin
    password: J-Y@WnAh8nJ#k2D%
  slave:
    url:  jdbc:postgresql://groyyo-postgres-db-dev.postgres.database.azure.com:5432/order_management_service
    username: groyyopgadmin
    password: J-Y@WnAh8nJ#k2D%
  checkout:
    timeout: '5000'

################## Kafka Properties ####################
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    consumer:
      fetch-max-wait: 100ms
      group-id: default
      enable-auto-commit: 'true'
      auto-offset-reset: earliest
      properties:
        fetch:
          max:
            bytes: '20971520'
        max:
          partition:
            fetch:
              bytes: '10485760'
      auto-commit-interval: '1000'
      max-poll-records: '200'
      fetch-min-size: '10'
    producer:
      acks: '1'
    properties:
      message:
        max:
          bytes: '21943040'
          request:
            size: '21943040'
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='55OIB55RPE623TER' password='plRVaF0F7m5yXMaAwrC5A5BiMYO2/KgRe/MB2XuT2raGyZexbx4vQ7sKeqxBaQdJ';
      retries: '1'
    #client-id: bootstrapServiceClient
    listener:
      type: batch
    admin:
      fail-fast: 'true'
    bootstrap-servers: pkc-7prvp.centralindia.azure.confluent.cloud:9092
  application:
    name: order-management-service
  main:
    allow-circular-references: true

############## Kafka Topics #############
kafka:
  consumer:
    autostart: 'false'
  base:
    topic: kafka-orderManagement-topic-dev
  master:
    updates:
      topic: master-data-updates-dev
  quality-management:
    topic: qc-taskAssignment-topic-dev
  notification:
    topic :  kafka-notification-topic-dev

############### healthcheck spring properties ###############
management:
  health:
    db:
      enabled: 'true'
    diskspace:
      enabled: 'true'
  endpoint:
    health:
      show-details: 'ALWAYS'
      
############### package config ###############
packages:
  repository:    com.groyyo.order.management.repository
  entityManager:  com.groyyo.order.management.entity

debug: 'false'

######################### multi-tenancy config #####################################
multitenancy:
  datasource-cache:
    maximumSize: 100
    expireAfterAccess: 10
  master:
    repository:
      packages: com.groyyo.core.multitenancy.multitenancy.repository
    entityManager:
      packages: com.groyyo.core.multitenancy.multitenancy.domain.entity
    datasource:
      url: jdbc:postgresql://groyyo-postgres-db-multi.postgres.database.azure.com:5432/master
      username: groyyopgadmin
      password: J-Y@WnAh8nJ#k2D%
      hikari:
        maximumPoolSize: 2
        minimumIdle: 0
        idleTimeout: 30000
    liquibase:
      enabled: false
  tenant:
    repository:
      packages: com.groyyo.order.management
    entityManager:
      packages: com.groyyo.order.management.entity
    datasource:
      url-prefix: jdbc:postgresql://groyyo-postgres-db-multi.postgres.database.azure.com:5432/
      hikari:
        maximumPoolSize: 2
        minimumIdle: 0
        idleTimeout: 30000
    liquibase:
      changeLog: classpath:changelog/changelog-tenant.yaml

issuerUri: https://authdev.groyyo.com/oauth2/jwks

encryption:
  secret: verySecret
  salt: jozo

azure:
  storage:
    ConnectionString: DefaultEndpointsProtocol=https;AccountName=groyyotenantstorage;AccountKey=Z0C14b9x66WuW5VcuAgt0vKMaC7bVlxqxQXcGaoZvyaCE+ZTKuqs39BWbjQhx9wASjUn86wRbIXP+AStnElvag==;EndpointSuffix=core.windows.net

