############# Application Context ###############
server:
  port: '8008'
  servlet:
    context-path: /order-management-service
  tomcat:
    max-threads: '50'
    accesslog:
      enabled: 'true'
      prefix: order-management-service
      pattern: '%h %l %u %t "%r" %I %s %b %F %D'
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: 'true'
      directory: /var/log/groyyo
  error:
    include-message: always

########## Services URL's ##############
service:
  user:
    url: https://preproderp.groyyo.com/user
  masterData:
    url: https://groyyoconsoledev.groyyo.com/master-data-service

############## Hibernate Configuration ##############
hibernate:
  format_sql: 'true'
  dialect: org.hibernate.dialect.PostgreSQL92Dialect
  order_inserts: 'true'
  order_updates: 'true'
  cache:
    provider_class: org.hibernate.cache.NoCacheProvider
  hbm2ddl:
    auto: update
  show_sql: 'false'

################# Postgresql JDBC Connection config ###############
jdbc:
  max:
    statements: 240
    idle:
      time:
        excess:
          connections: 20
      timing: 30
    pool:
      size: '20'
  min:
    pool:
      size: '2'
  test:
    connection:
      on:
        checkin: true
  initial:
    pool:
      size: '2'
  driver:
    class:
      name: org.postgresql.Driver
  preferred:
    test:
      query: SELECT 1
  acquire:
    increment: '2'
  master:
    url:  jdbc:postgresql://groyyo-postgres-db-dev.postgres.database.azure.com:5432/order_management_service
    username: groyyopgadmin
    password: J-Y@WnAh8nJ#k2D%
  slave:
    url:  jdbc:postgresql://groyyo-postgres-db-dev.postgres.database.azure.com:5432/order_management_service
    username: groyyopgadmin
    password: J-Y@WnAh8nJ#k2D%
  checkout:
    timeout: '5000'

################## Kafka Properties ####################
spring:
  kafka:
    consumer:
      fetch-max-wait: 100ms
      group-id: default
      enable-auto-commit: 'true'
      auto-offset-reset: earliest
      properties:
        fetch:
          max:
            bytes: '20971520'
        max:
          partition:
            fetch:
              bytes: '10485760'
      auto-commit-interval: '1000'
      max-poll-records: '200'
      fetch-min-size: '10'
    producer:
      acks: '1'
    properties:
      message:
        max:
          bytes: '21943040'
          request:
            size: '21943040'
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='55OIB55RPE623TER' password='plRVaF0F7m5yXMaAwrC5A5BiMYO2/KgRe/MB2XuT2raGyZexbx4vQ7sKeqxBaQdJ';
      retries: '1'
    #client-id: bootstrapServiceClient
    listener:
      type: batch
    admin:
      fail-fast: 'true'
    bootstrap-servers: pkc-7prvp.centralindia.azure.confluent.cloud:9092
  application:
    name: order-management-service

############## Kafka Topics #############
kafka:
  consumer:
    autostart: 'false'
  base:
    topic: kafka-orderManagement-topic

############### healthcheck spring properties ###############
management:
  health:
    db:
      enabled: 'true'
    diskspace:
      enabled: 'true'
  endpoint:
    health:
      show-details: 'ALWAYS'
packages:
  repository:    com.groyyo.order.management.repository
  entityManager:  com.groyyo.order.management.entity

debug: 'false'

