apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-tenant-management-service-prod
spec:
  selector:
    matchLabels:
      app: multi-tenant-management-service-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: multi-tenant-management-service-prod
        group: service-prod
    spec:
      containers:
        - image: groyyoOrgServiceRegistry.azurecr.io/multi-tenant-management-service-prod:latest
          name: multi-tenant-management-service-prod
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
