apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service
spec:
  selector:
    matchLabels:
      app: order-management-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-management-service
        group: service-dev
    spec:
      containers:
        - image: groyyoOrgServiceRegistry.azurecr.io/order-management-service-dev:latest
          name: order-management-service
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
