apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-service-prod
spec:
  selector:
    matchLabels:
      app: oauth-service-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: oauth-service-prod
        group: service-prod
    spec:
      containers:
        - image: groyyoOrgServiceRegistry.azurecr.io/oauth-service-prod:backup
          name: oauth-service-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "128m"
            limits:
              memory: "1024Mi"
              cpu: "256m"
          ports:
            - containerPort: 80
