apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service-uat
spec:
  selector:
    matchLabels:
      app: order-management-service-uat
  replicas: 1
  template:
    metadata:
      labels:
        app: order-management-service-uat
        group: service-uat
    spec:
      containers:
        - image: groyyoOrgServiceRegistry.azurecr.io/order-management-service-uat:latest
          name: order-management-service-uat
          resources:
            requests:
              memory: "500Mi"
              cpu: "128m"
            limits:
              memory: "1024Mi"
              cpu: "256m"
          ports:
            - containerPort: 80
