apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service-prod
spec:
  selector:
    matchLabels:
      app: order-management-service-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: order-management-service-prod
        group: service-prod
    spec:
      containers:
        - image: groyyoqcacr.azurecr.io/order-management-service-prod:latest
          name: order-management-service-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 80