apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service
spec:
  selector:
    matchLabels:
      app: order-management-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-management-service
        group: service-dev
    spec:
      containers:
        - image: groyyoacrmulti.azurecr.io/order-management-service-dev:backup
          name: order-management-service
          env:
            - name: TZ
              value: Asia/Kolkata
          resources:
            requests:
              memory: "500Mi"
              cpu: "64m"
            limits:
              memory: "1024Mi"
              cpu: "128m"
          ports:
            - containerPort: 80
