apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-service-uat
spec:
  selector:
    matchLabels:
      app: oauth-service-uat
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-service-uat
        group: service-uat
    spec:
      containers:
        - image: groyyoOrgServiceRegistry.azurecr.io/oauth-service-uat:backup
          name: oauth-service-uat
          resources:
            requests:
              memory: "500Mi"
              cpu: "128m"
            limits:
              memory: "1024Mi"
              cpu: "256m"
          ports:
            - containerPort: 80
