apiVersion: v1
kind: Service
metadata:
  name: order-management-service-prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8008
      name: http
  selector:
    app: order-management-service-prod
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-management-service-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-qc-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - intent.groyyo.com
      secretName: letsencrypt-qc-prod
  rules:
    - host: intent.groyyo.com
      http:
        paths:
          - path: /order-management-service
            pathType: Prefix
            backend:
              service:
                name: order-management-service-prod
                port:
                  number: 80