apiVersion: v1
kind: Service
metadata:
  name: order-management-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8008
      name: http
  selector:
    app: order-management-service
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-management-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-auth-dev
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - intent-multi.groyyo.com
      secretName: letsencrypt-auth-dev
  rules:
    - host: intent-multi.groyyo.com
      http:
        paths:
          - path: /order-management-service
            pathType: Prefix
            backend:
              service:
                name: order-management-service
                port:
                  number: 80
