#Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: order-management-service-deployment-action-dev

on:
  push:
    branches: [ 'feature/multi']

jobs:
  deploy-service:
    if: |-
      ${{ (!contains(github.event.head_commit.message, '#md '))}}
    uses: ./.github/workflows/service-deployment-workflow.yml
    with:
      env: "dev"
      cluster-name: "groyyo-ks-cluster-multi"
      resource-group: "groyyo-rg-multi"
      docker-file: "Dockerfile.dev"
      service: "order-management-service"
      service-file: "service-dev"
      test-file: "integration-test/groyyo-create-organization"
      test-required: "false"
      container-image: "order-management-service-dev:latest"
      container-image-backup: "order-management-service-dev:backup"
      deployment-file: "deployment-dev"
      deployment-file-rollback: "deployment-dev-rollback"
      is-prod: "false"
      is-version-change: "true"
      network-policy-file: "network-policy-dev"
    secrets:
      AZURE_REGISTRY_LOGINURL: "${{ secrets.AZURE_REGISTRY_LOGINURL_MULTI }}"
      AZURE_REGISTRY_PASSWORD: "${{ secrets.AZURE_REGISTRY_PASSWORD_MULTI }}"
      AZURE_REGISTRY_USERNAME: "${{ secrets.AZURE_REGISTRY_USERNAME_MULTI }}"
      AZURE_CREDENTIALS_QC_CLUSTER: "${{ secrets.AZURE_CREDENTIALS_CLUSTER_MULTI }}"
      AZURE_SUBSCRIPTION_ID_NEW_CLUSTER: "${{ secrets.AZURE_SUBSCRIPTION_ID_NEW_CLUSTER }}"
      DISCORD_WEBHOOK: "${{ secrets.DISCORD_WEBHOOK }}"
      GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
